disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - variable_name
  - vertical_whitespace
opt_in_rules:
  - empty_count
  - redundant_nil_coalescing
excluded:
  - Pods
